[package]
name = "ipc"
version = "0.1.0"
authors = ["Alex Whitney <awhitney@tylercapital.co.uk>"]

[dependencies.rkdb]
path = "../.."
features = ["api"]

# [dependencies]
# rkdb = { git = "https://github.com/jfenton/rkdb", branch = "master", features = ["api"], optional = true }

